steps:
  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/kansas-beta-backend', './backend']
    id: 'build-backend'


  # Build frontend Docker image
  # Note: Frontend env vars are baked into the build at build time
  # VITE_API_URL: Uses _FRONTEND_API_URL substitution (provided by deploy.sh)
  # For full deployments, deploy.sh fetches the backend URL before starting the build
  # For frontend-only deployments, deploy.sh also fetches and passes the URL
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=${_FRONTEND_API_URL}'
      - '--build-arg'
      - 'VITE_APP_NAME=${_APP_NAME}'
      - '--build-arg'
      - 'VITE_APP_VERSION=${_APP_VERSION}'
      - '--build-arg'
      - 'VITE_AUTH0_DOMAIN=${_VITE_AUTH0_DOMAIN}'
      - '--build-arg'
      - 'VITE_AUTH0_CLIENT_ID=${_VITE_AUTH0_CLIENT_ID}'
      - '--build-arg'
      - 'VITE_AUTH0_AUDIENCE=${_VITE_AUTH0_AUDIENCE}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kansas-beta-frontend'
      - './frontend'
    id: 'build-frontend'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kansas-beta-backend']
    id: 'push-backend'
    waitFor: ['build-backend']

  # Run database migrations
  # This step runs migrations before deploying the app
  # Uses ts-node to run TypeScript migrations directly (no build needed)
  # DATABASE_PASSWORD is injected from Secret Manager via secretEnv
  # Uses Cloud SQL Proxy for TCP connection (more reliable in Cloud Build)
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        npm ci --production=false
        
        # Download and start Cloud SQL Proxy
        echo "Downloading Cloud SQL Proxy..."
        wget -q https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.0/cloud-sql-proxy.linux.amd64 -O cloud-sql-proxy
        chmod +x cloud-sql-proxy
        
        echo "Starting Cloud SQL Proxy in background..."
        ./cloud-sql-proxy $PROJECT_ID:us-central1:${_DATABASE_INSTANCE} --port=5432 > /tmp/cloud-sql-proxy.log 2>&1 &
        PROXY_PID=$$!
        
        # Wait for proxy to be ready (check log for success message)
        echo "Waiting for Cloud SQL Proxy to be ready..."
        for i in {1..30}; do
          if grep -q "ready for new connections" /tmp/cloud-sql-proxy.log 2>/dev/null; then
            echo "Cloud SQL Proxy is ready!"
            # Give it a moment to fully initialize
            sleep 2
            break
          fi
          echo "Attempt $$i/30: Proxy not ready, waiting..."
          sleep 1
        done
        
        if ! grep -q "ready for new connections" /tmp/cloud-sql-proxy.log 2>/dev/null; then
          echo "ERROR: Cloud SQL Proxy failed to start"
          echo "Proxy logs:"
          cat /tmp/cloud-sql-proxy.log || true
          kill $$PROXY_PID 2>/dev/null || true
          exit 1
        fi
        
        echo "Running migrations..."
        npm run migration:run
        MIGRATION_EXIT=$$?
        
        # Clean up proxy
        kill $$PROXY_PID 2>/dev/null || true
        exit $$MIGRATION_EXIT
    id: 'run-migrations'
    waitFor: ['push-backend']
    env:
      - 'NODE_ENV=production'
      - 'DATABASE_HOST=127.0.0.1'
      - 'DATABASE_PORT=5432'
      - 'DATABASE_NAME=${_DATABASE_NAME}'
      - 'DATABASE_USER=${_DATABASE_USER}'
      - 'GCP_SECRET_MANAGER_ENABLED=true'
      - 'GCP_PROJECT_ID=$PROJECT_ID'
    secretEnv: ['DATABASE_PASSWORD']

  # Run database seeders
  # This step runs seeders after migrations to populate initial data
  # Uses ts-node to run TypeScript seeders directly (no build needed)
  # DATABASE_PASSWORD is injected from Secret Manager via secretEnv
  # Uses Cloud SQL Proxy for TCP connection (more reliable in Cloud Build)
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        npm ci --production=false
        
        # Download and start Cloud SQL Proxy
        echo "Downloading Cloud SQL Proxy..."
        wget -q https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.0/cloud-sql-proxy.linux.amd64 -O cloud-sql-proxy
        chmod +x cloud-sql-proxy
        
        echo "Starting Cloud SQL Proxy in background..."
        ./cloud-sql-proxy $PROJECT_ID:us-central1:${_DATABASE_INSTANCE} --port=5432 > /tmp/cloud-sql-proxy.log 2>&1 &
        PROXY_PID=$$!
        
        # Wait for proxy to be ready (check log for success message)
        echo "Waiting for Cloud SQL Proxy to be ready..."
        for i in {1..30}; do
          if grep -q "ready for new connections" /tmp/cloud-sql-proxy.log 2>/dev/null; then
            echo "Cloud SQL Proxy is ready!"
            # Give it a moment to fully initialize
            sleep 2
            break
          fi
          echo "Attempt $$i/30: Proxy not ready, waiting..."
          sleep 1
        done
        
        if ! grep -q "ready for new connections" /tmp/cloud-sql-proxy.log 2>/dev/null; then
          echo "ERROR: Cloud SQL Proxy failed to start"
          echo "Proxy logs:"
          cat /tmp/cloud-sql-proxy.log || true
          kill $$PROXY_PID 2>/dev/null || true
          exit 1
        fi
        
        echo "Running seeders..."
        npm run seed:run
        SEEDER_EXIT=$$?
        
        # Clean up proxy
        kill $$PROXY_PID 2>/dev/null || true
        exit $$SEEDER_EXIT
    id: 'run-seeders'
    waitFor: ['run-migrations']
    env:
      - 'NODE_ENV=production'
      - 'DATABASE_HOST=127.0.0.1'
      - 'DATABASE_PORT=5432'
      - 'DATABASE_NAME=${_DATABASE_NAME}'
      - 'DATABASE_USER=${_DATABASE_USER}'
      - 'GCP_SECRET_MANAGER_ENABLED=true'
      - 'GCP_PROJECT_ID=$PROJECT_ID'
    secretEnv: ['DATABASE_PASSWORD']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kansas-beta-frontend']
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'kansas-beta-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kansas-beta-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:${_DATABASE_INSTANCE}'
    id: 'deploy-backend'
    waitFor: ['run-seeders']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'kansas-beta-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kansas-beta-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

images:
  - 'gcr.io/$PROJECT_ID/kansas-beta-backend'
  - 'gcr.io/$PROJECT_ID/kansas-beta-frontend'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

substitutions:
  _FRONTEND_API_URL: ''  # Optional: Will be fetched from Cloud Run if not provided
  _APP_NAME: 'Kansas Beta'
  _APP_VERSION: '1.0.0'
  _DATABASE_NAME: 'kansas_beta'
  _DATABASE_INSTANCE: 'kansas-beta-db'
  _DATABASE_USER: 'postgres'
  _VITE_AUTH0_DOMAIN: ''  # Optional: Set via --substitutions or will be empty
  _VITE_AUTH0_CLIENT_ID: ''  # Optional: Set via --substitutions or will be empty
  _VITE_AUTH0_AUDIENCE: ''  # Optional: Set via --substitutions or will be empty
  # DATABASE_PASSWORD is injected from Secret Manager via availableSecrets below

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/database-password/versions/latest
      env: 'DATABASE_PASSWORD'

