steps:
  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/kansas-beta-backend', './backend']
    id: 'build-backend'

  # Build frontend Docker image
  # Note: Frontend env vars are baked into the build at build time
  # They can come from:
  # 1. Cloud Build substitution variables (--substitutions)
  # 2. Secret Manager (accessed during build)
  # 3. Environment variables set in this step
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=${_FRONTEND_API_URL}'
      - '--build-arg'
      - 'VITE_APP_NAME=${_APP_NAME:-Kansas Beta}'
      - '--build-arg'
      - 'VITE_APP_VERSION=${_APP_VERSION:-1.0.0}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kansas-beta-frontend'
      - './frontend'
    id: 'build-frontend'
    env:
      - 'VITE_API_URL=${_FRONTEND_API_URL}'
      - 'VITE_APP_NAME=${_APP_NAME:-Kansas Beta}'

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kansas-beta-backend']
    id: 'push-backend'
    waitFor: ['build-backend']

  # Run database migrations
  # This step runs migrations before deploying the app
  # Uses Node.js to run migrations with Cloud SQL connection
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend
        npm ci --production=false
        npm run migration:run
    id: 'run-migrations'
    waitFor: ['push-backend']
    env:
      - 'NODE_ENV=production'
      - 'DATABASE_HOST=/cloudsql/$PROJECT_ID:us-central1:${_DATABASE_INSTANCE:-kansas-beta-db}'
      - 'DATABASE_NAME=${_DATABASE_NAME:-kansas_beta}'
      - 'DATABASE_USER=${_DATABASE_USER:-postgres}'
      - 'GCP_SECRET_MANAGER_ENABLED=true'
      - 'GCP_PROJECT_ID=$PROJECT_ID'
    # Connect to Cloud SQL instance via Unix socket
    volumes:
      - name: 'cloudsql'
        path: /cloudsql
    # Note: DATABASE_PASSWORD should be loaded from Secret Manager
    # The migration script will use Secret Manager to get the password

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kansas-beta-frontend']
    id: 'push-frontend'
    waitFor: ['build-frontend']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'kansas-beta-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kansas-beta-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:${_DATABASE_INSTANCE:-kansas-beta-db}'
    id: 'deploy-backend'
    waitFor: ['run-migrations']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'kansas-beta-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/kansas-beta-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
    id: 'deploy-frontend'
    waitFor: ['push-frontend']

images:
  - 'gcr.io/$PROJECT_ID/kansas-beta-backend'
  - 'gcr.io/$PROJECT_ID/kansas-beta-frontend'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

substitutions:
  _FRONTEND_API_URL: ''  # Will be set dynamically based on backend URL
  _APP_NAME: 'Kansas Beta'
  _APP_VERSION: '1.0.0'
  _DATABASE_NAME: 'kansas_beta'
  _DATABASE_INSTANCE: 'kansas-beta-db'
  _DATABASE_USER: 'postgres'
  # _DATABASE_PASSWORD should be set via Secret Manager or Cloud Build secrets

